#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f {{ source_file() }} --list

build:
  #!/usr/bin/env bash
  set -eufo pipefail

  docker buildx build --platform linux/amd64,linux/arm64 -t devcontainer-feature/hello:1 .

dive:
  #!/usr/bin/env bash
  set -eufo pipefail

  dive devcontainer-feature/hello:1
  